# Generated by Django 6.1.1 on 2026-09-14 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("web_page", "Web Page"),
                            ("raw_link", "Raw Link"),
                            ("note", "Note"),
                            ("quote", "Quote"),
                            ("image", "Image"),
                            ("markdown", "Markdown"),
                            ("pdf", "PDF"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("source_url", models.URLField(blank=True, max_length=2000, null=True)),
                (
                    "attribution",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "local_asset_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_fetched", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ArtifactHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_text", models.TextField()),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("yellow", "Yellow"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("pink", "Pink"),
                            ("red", "Red"),
                        ],
                        default="yellow",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="lumen.artifact",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="artifact",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="lumen.project",
            ),
        ),
        migrations.CreateModel(
            name="ArtifactTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact_tags",
                        to="lumen.artifact",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("artifact", "name"), name="unique_artifact_tag"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ArtifactLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("related", "Related"),
                            ("supports", "Supports"),
                            ("contradicts", "Contradicts"),
                            ("background", "Background"),
                            ("quotes", "Quotes"),
                            ("depends_on", "Depends on"),
                        ],
                        default="related",
                        max_length=50,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="lumen.artifact",
                    ),
                ),
                (
                    "target_artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="lumen.artifact",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact_links",
                        to="lumen.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_artifact", "target_artifact"),
                        name="unique_artifact_link",
                    )
                ],
            },
        ),
    ]
